/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Demether } from "./Demether";
export * as factories from "./factories";
export { Demether__factory } from "./factories/Demether__factory";
